export {
  subscribeToUserData,
  getUserData,
  createUserData,
  joinUserToRoom,
  updateUserNickname,
  updateUserExamTarget,
  updateAlwaysOnVideo,
  updateUserPresence,
  subscribeToCourses,
  getCourses,
  updateCourseProgress,
  seedDefaultCourses,
  subscribeToAssignments,
  getAssignments,
  addAssignment,
  toggleAssignment,
  deleteAssignment,
  subscribeToNotes,
  getNotes,
  addNote,
  deleteNote,
  seedCurriculum,
  leaveRoom,
} from "@/lib/supabaseService";
